'use client';

import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Download, Send } from 'lucide-react';
import { toPng } from 'html-to-image';
import { useRef } from 'react';

interface ReportCardProps {
  title: string;
  date: string;
  children: React.ReactNode;
}

export default function ReportCard({ title, date, children }: ReportCardProps) {
  const reportRef = useRef<HTMLDivElement>(null);

  const handleDownload = async () => {
    if (!reportRef.current) return;
    
    try {
      const dataUrl = await toPng(reportRef.current, { 
        cacheBust: true,
        backgroundColor: '#ffffff', // 흰색 배경 강제
      });
      
      const link = document.createElement('a');
      link.download = `${title}_${date}.png`;
      link.href = dataUrl;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
    } catch (error: any) {
      console.error('Download failed:', error);
      alert(`리포트 다운로드에 실패했습니다: ${error.message || '알 수 없는 오류'}`);
    }
  };

  const handleSendToSlack = () => {
    // 실제 Slack 전송 로직은 서버 액션으로 구현해야 함
    // 여기서는 알림만 표시
    alert('Slack 전송 기능은 준비 중입니다.');
  };

  return (
    <div className="space-y-4">
      <div className="flex justify-end gap-2 no-print">
        <Button variant="outline" size="sm" onClick={handleDownload}>
          <Download className="mr-2 h-4 w-4" />
          이미지 저장
        </Button>
        <Button size="sm" onClick={handleSendToSlack}>
          <Send className="mr-2 h-4 w-4" />
          Slack 전송
        </Button>
      </div>

      <div ref={reportRef} className="bg-white dark:bg-slate-950 p-4 rounded-lg border shadow-sm">
        <div className="mb-6 text-center border-b pb-4">
          <h2 className="text-2xl font-bold">{title}</h2>
          <p className="text-muted-foreground">{date}</p>
        </div>
        
        {children}
        
        <div className="mt-12 pt-4 border-t text-center text-xs text-muted-foreground">
          Generated by F&B Dashboard
        </div>
      </div>
    </div>
  );
}
